version: '3.9'

services:
  frontend:
    container_name: kitchenify_Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /frontend
    depends_on:
      - backend
    restart: always

  backend:
    container_name: kitchenify_Backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    working_dir: /backend
    restart: always
    depends_on:
      - postgres


  postgres:
    build:
      context: ./DB
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER:postgres
      POSTGRES_PASSWORD:mypassword
      POSTGRES_DB:RECETAS
    ports:
      - "5432:5432"

