version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  postgres:
    build:
      context: ./DB
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
